### ISSUE TITLE
difference in numbers

### ISSUE THREAD

**Issue by Cyberdada** [codler/sweden-coronavirus#2]
Hi,
Why does platz.se say 391 dead, 
while fohm says 373?

(2020-04-05)

**Comment by codler** [comment]
The numbers are from each Regions official websites gathered together, they update numbers faster.

**Comment by johanneswilm** [comment]
@codler Actually that's not really the case. I have checked some of your numbers from Skåne and they don't always match up with what you are reporting. Your site is being used by news media worldwide as their source of truth about Swedish numbers. If you are not able to keep up with the official statistics, it would probably be better to take your site down and forward people to the official statistics. Think about it - there are lots of countries evaluating their strategies and if they get incorrect numbers from Sweden, then that will have an impact on their decisions and by extension also on the number of deaths in those countries.

**Comment by johanneswilm** [comment]
@codler COuld you try to explain how you calculate those numbers? Take for example the latest figure for Stockholm you posted today - 231 new cases for 2020-04-14. As source for that number you link to this page: https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/bekraftade-fall-i-sverige . Yet on that page the number "231" doesn't appear. If I click on download of the raw data on that page, for Stockholm it lists "201" for 2020-04-13 and "95" for 2020-04-14. 2020-04-14 is today, so the number is not complete which is why you maybe picked yesterday. But that's not the right number either.

So where is that number "231" coming from?
